// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DKNet.Notification.App.BDDTests.Features.Notifications
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Email channel with the SMTP sender, rendering and delivery")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class EmailChannelWithTheSMTPSenderRenderingAndDeliveryFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Notifications", "Email channel with the SMTP sender, rendering and delivery", "", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EmailChannel.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Notifications/EmailChannel.feature.ndjson", 27);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An email call is skipped when email is not ready for it")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("email off", "account-opened", "ChannelNotConfigured", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("email on with the sender \"Graph\"", "account-opened", "ChannelNotConfigured", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("email set up to the mail catcher, and a template \"team-digest\" with only a Teams " +
            "version", "team-digest", "NoTemplateVersion", "2", null)]
        public async global::System.Threading.Tasks.Task AnEmailCallIsSkippedWhenEmailIsNotReadyForIt(string set_Up, string template, string reason, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("set-up", set_Up);
            argumentsOfScenario.Add("template", template);
            argumentsOfScenario.Add("reason", reason);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email call is skipped when email is not ready for it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email call that cannot be delivered is skipped before its recipient is checked" +
                    "", null, tagsOfRule);
#line 16
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync(string.Format("the service runs with sign-in on and {0}", set_Up), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"{0}\" with no recipient", template), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
      await testRunner.AndAsync(string.Format("the skip warning names reason \"{0}\", and the accepted count for \"email\" with outc" +
                            "ome \"skipped\" rose by 1", reason), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Every other channel is still skipped")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("teams", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("whatsapp", "4", null)]
        public async global::System.Threading.Tasks.Task EveryOtherChannelIsStillSkipped(string channel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("channel", channel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Every other channel is still skipped", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email call that cannot be delivered is skipped before its recipient is checked" +
                    "", null, tagsOfRule);
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" sends template \"account-opened\" to \"jane@example.com\" on channel \"" +
                            "{0}\"", channel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
      await testRunner.AndAsync("the skip warning names reason \"ChannelNotSupported\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A missing or bad recipient is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no address", "RECIPIENT_MISSING", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("an empty address", "RECIPIENT_MISSING", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"Jane <jane@example.com>\"", "RECIPIENT_INVALID", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"a@example.com,b@example.com\"", "RECIPIENT_INVALID", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"jane.example.com\"", "RECIPIENT_INVALID", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("\" jane@example.com\"", "RECIPIENT_INVALID", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("an address of 255 characters", "RECIPIENT_INVALID", "11", null)]
        public async global::System.Threading.Tasks.Task AMissingOrBadRecipientIsRefused(string recipient, string code, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("recipient", recipient);
            argumentsOfScenario.Add("code", code);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A missing or bad recipient is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The recipient and every token are checked before the call is queued", null, tagsOfRule);
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"account-opened\" to {0} for customer \"Jane Tan\" an" +
                            "d account \"0012345678\"", recipient), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
      await testRunner.ThenAsync(string.Format("the call is refused with \"{0}\" for the recipient, and a trace id", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
      await testRunner.AndAsync(string.Format("1 rejection entry is logged with \"{0}\", and the rejected count for \"{0}\" rose by " +
                            "1", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A missing parameter is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AMissingParameterIsRefused()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A missing parameter is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The recipient and every token are checked before the call is queued", null, tagsOfRule);
#line 68
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" with no account", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
      await testRunner.ThenAsync("the call is refused with \"PARAMETER_MISSING\" naming \"accountNumber\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
      await testRunner.AndAsync("1 rejection entry is logged with \"PARAMETER_MISSING\", and the rejected count for " +
                        "\"PARAMETER_MISSING\" rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A full queue answers 503")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AFullQueueAnswers503()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A full queue answers 503", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A full queue refuses new calls", null, tagsOfRule);
#line 77
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
      await testRunner.GivenAsync("the service runs with sign-in on, email set up to send to the mail catcher and a " +
                        "queue size of 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
      await testRunner.AndAsync("2 notifications of \"treasury-ops\" are not delivered yet, because the mail catcher" +
                        " is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
      await testRunner.ThenAsync("the call is refused with \"QUEUE_FULL\", status 503 and a retry after 30 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 83
      await testRunner.AndAsync("1 rejection entry is logged with \"QUEUE_FULL\", the rejected count for \"QUEUE_FULL" +
                        "\" rose by 1, and the queue length shows 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A set-up email sender is logged at start-up")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ASet_UpEmailSenderIsLoggedAtStart_Up()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A set-up email sender is logged at start-up", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 88
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
      await testRunner.GivenAsync("email is on, with the sender \"Smtp\" and every SMTP setting given", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
      await testRunner.WhenAsync("the service starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
      await testRunner.ThenAsync("1 start-up entry names the email sender \"Smtp\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
      await testRunner.AndAsync("no warning says email is not set up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email off logs no email start-up entry")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task EmailOffLogsNoEmailStart_UpEntry()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email off logs no email start-up entry", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 95
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
      await testRunner.GivenAsync("email is off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
      await testRunner.WhenAsync("the service starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
      await testRunner.ThenAsync("no email start-up entry is logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email on but not set up still lets the service start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no mail server host", "the mail server host", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("no sender address", "the sender address", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender address \"notify.example.com\"", "the sender address", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("the port 70000", "the port", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("the security mode \"None\"", "the security mode", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("a time limit of 500 seconds", "the time limit", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\"", "the sender choice", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"SendGrid\"", "the sender choice", "23", null)]
        public async global::System.Threading.Tasks.Task EmailOnButNotSetUpStillLetsTheServiceStart(string fault, string setting, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            argumentsOfScenario.Add("setting", setting);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email on but not set up still lets the service start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 101
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 102
      await testRunner.GivenAsync(string.Format("the service started with email on and {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
      await testRunner.ThenAsync("the call is accepted and skipped with reason \"ChannelNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 106
      await testRunner.AndAsync(string.Format("the start-up wrote 1 warning that email is not set up, naming {0} and no setting " +
                            "value", setting), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A settings change takes effect only at the next start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ASettingsChangeTakesEffectOnlyAtTheNextStart()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A settings change takes effect only at the next start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 120
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 121
      await testRunner.GivenAsync("the service started with email off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
      await testRunner.AndAsync("the email settings are turned on while the service runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
      await testRunner.ThenAsync("the call is accepted and skipped with reason \"ChannelNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
