// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DKNet.Notification.App.BDDTests.Features.Notifications
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Email channel with the SMTP sender, rendering and delivery")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class EmailChannelWithTheSMTPSenderRenderingAndDeliveryFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Notifications", "Email channel with the SMTP sender, rendering and delivery", "", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EmailChannel.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Notifications/EmailChannel.feature.ndjson", 51);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An email reaches the recipient")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AnEmailReachesTheRecipient()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email reaches the recipient", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid email call is rendered, queued and delivered", null, tagsOfRule);
#line 22
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
      await testRunner.AndAsync("the mail catcher holds 1 mail to \"jane@example.com\" with the subject \"Your accoun" +
                        "t is open\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
      await testRunner.AndAsync("the mail says \"Dear Jane Tan, your account 0012345678 is open.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
      await testRunner.AndAsync("the mail comes from the sender address and sender name of the settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
      await testRunner.AndAsync("the mail has no other recipient, no attachment and an HTML body only", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A delivery is logged and counted")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ADeliveryIsLoggedAndCounted()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A delivery is logged and counted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid email call is rendered, queued and delivered", null, tagsOfRule);
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
      await testRunner.ThenAsync("1 queued entry and 1 delivered entry on attempt 1 are logged for the notification" +
                        " id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
      await testRunner.AndAsync("both entries carry the trace id of the call", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
      await testRunner.AndAsync("the accepted count for \"email\" with outcome \"queued\" and the delivered count for " +
                        "\"email\" each rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
      await testRunner.AndAsync("1 delivery duration is recorded for \"email\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("No personal data or secret reaches the logs")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task NoPersonalDataOrSecretReachesTheLogs()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No personal data or secret reaches the logs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid email call is rendered, queued and delivered", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
      await testRunner.GivenAsync("the mail catcher asks the service to sign in with the password \"Pa55-w0rd-7781\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
      await testRunner.ThenAsync("the mail catcher holds 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
      await testRunner.AndAsync("no log entry, trace or kept idempotency record holds \"jane@example.com\", \"Jane Ta" +
                        "n\", \"0012345678\" or \"Pa55-w0rd-7781\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A value cannot add markup to the mail")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AValueCannotAddMarkupToTheMail()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A value cannot add markup to the mail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid email call is rendered, queued and delivered", null, tagsOfRule);
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"<b>Jane</b>\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
      await testRunner.ThenAsync("the mail shows \"<b>Jane</b>\" as text, not in bold", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A value cannot add a mail header")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AValueCannotAddAMailHeader()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A value cannot add a mail header", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid email call is rendered, queued and delivered", null, tagsOfRule);
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
      await testRunner.GivenAsync("the template \"account-alert\" has the email subject \"Alert for {{customerName}}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-alert\" to \"jane@example.com\" for customer" +
                        " \"Jane\", a line feed and \"Bcc: eve@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
      await testRunner.ThenAsync("the mail\'s subject is \"Alert for Jane Bcc: eve@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
      await testRunner.AndAsync("the mail has only the recipient \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Of 2 names that differ only in case, the first in the call fills the token")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task Of2NamesThatDifferOnlyInCaseTheFirstInTheCallFillsTheToken()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Of 2 names that differ only in case, the first in the call fills the token", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The template is filled from the parameters", "", tagsOfRule);
#line 62
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" with \"custo" +
                        "merName\" set to \"Jane\", then \"CustomerName\" set to \"John\", and account \"00123456" +
                        "78\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
      await testRunner.ThenAsync("the mail says \"Dear Jane, your account 0012345678 is open.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An email call is skipped when email is not ready for it")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("email off", "account-opened", "ChannelNotConfigured", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("email on with the sender \"SendGrid\"", "account-opened", "ChannelNotConfigured", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("email set up to the mail catcher, and a template \"team-digest\" with only a Teams " +
            "version", "team-digest", "NoTemplateVersion", "8", null)]
        public async global::System.Threading.Tasks.Task AnEmailCallIsSkippedWhenEmailIsNotReadyForIt(string set_Up, string template, string reason, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("set-up", set_Up);
            argumentsOfScenario.Add("template", template);
            argumentsOfScenario.Add("reason", reason);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email call is skipped when email is not ready for it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email call that cannot be delivered is skipped before its recipient is checked" +
                    "", null, tagsOfRule);
#line 71
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
      await testRunner.GivenAsync(string.Format("the service runs with sign-in on and {0}", set_Up), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"{0}\" with no recipient", template), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 76
      await testRunner.AndAsync(string.Format("the skip warning names reason \"{0}\", and the accepted count for \"email\" with outc" +
                            "ome \"skipped\" rose by 1", reason), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Every other channel is still skipped")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("whatsapp", "9", null)]
        public async global::System.Threading.Tasks.Task EveryOtherChannelIsStillSkipped(string channel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("channel", channel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Every other channel is still skipped", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email call that cannot be delivered is skipped before its recipient is checked" +
                    "", null, tagsOfRule);
#line 86
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" sends template \"account-opened\" to \"jane@example.com\" on channel \"" +
                            "{0}\"", channel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
      await testRunner.AndAsync("the skip warning names reason \"ChannelNotSupported\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A missing or bad recipient is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no address", "RECIPIENT_MISSING", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("an empty address", "RECIPIENT_MISSING", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"Jane <jane@example.com>\"", "RECIPIENT_INVALID", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"a@example.com,b@example.com\"", "RECIPIENT_INVALID", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("\"jane.example.com\"", "RECIPIENT_INVALID", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("\" jane@example.com\"", "RECIPIENT_INVALID", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("an address of 255 characters", "RECIPIENT_INVALID", "16", null)]
        public async global::System.Threading.Tasks.Task AMissingOrBadRecipientIsRefused(string recipient, string code, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("recipient", recipient);
            argumentsOfScenario.Add("code", code);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A missing or bad recipient is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The recipient and every token are checked before the call is queued", null, tagsOfRule);
#line 105
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 102
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"account-opened\" to {0} for customer \"Jane Tan\" an" +
                            "d account \"0012345678\"", recipient), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
      await testRunner.ThenAsync(string.Format("the call is refused with \"{0}\" for the recipient, and a trace id", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
      await testRunner.AndAsync(string.Format("1 rejection entry is logged with \"{0}\", and the rejected count for \"{0}\" rose by " +
                            "1", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A missing parameter is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AMissingParameterIsRefused()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A missing parameter is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The recipient and every token are checked before the call is queued", null, tagsOfRule);
#line 122
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 102
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" with no account", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
      await testRunner.ThenAsync("the call is refused with \"PARAMETER_MISSING\" naming \"accountNumber\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
      await testRunner.AndAsync("1 rejection entry is logged with \"PARAMETER_MISSING\", and the rejected count for " +
                        "\"PARAMETER_MISSING\" rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
      await testRunner.AndAsync("the mail catcher receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A full queue answers 503")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AFullQueueAnswers503()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A full queue answers 503", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A full queue refuses new calls", null, tagsOfRule);
#line 131
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 132
      await testRunner.GivenAsync("the service runs with sign-in on, email set up to send to the mail catcher and a " +
                        "queue size of 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 133
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
      await testRunner.AndAsync("2 notifications of \"treasury-ops\" are not delivered yet, because the mail catcher" +
                        " is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 136
      await testRunner.ThenAsync("the call is refused with \"QUEUE_FULL\", status 503 and a retry after 30 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 137
      await testRunner.AndAsync("1 rejection entry is logged with \"QUEUE_FULL\", the rejected count for \"QUEUE_FULL" +
                        "\" rose by 1, and the queue length shows 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Each failure is retried or not by its kind")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the SMTP reply 451", "transient", "the mail is delivered on attempt 2", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("a mail server that does not answer in time", "transient", "the mail is delivered on attempt 2", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("a refused connection", "transient", "the mail is delivered on attempt 2", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("the SMTP reply 550", "permanent", "the notification fails with no attempt 2", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("the SMTP reply 535 for the sign-in", "permanent", "the notification fails with no attempt 2", "23", null)]
        public async global::System.Threading.Tasks.Task EachFailureIsRetriedOrNotByItsKind(string failure, string kind, string outcome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("failure", failure);
            argumentsOfScenario.Add("kind", kind);
            argumentsOfScenario.Add("outcome", outcome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each failure is retried or not by its kind", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A transient failure is retried, at most 3 attempts in all", null, tagsOfRule);
#line 146
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 142
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
      await testRunner.GivenAsync(string.Format("attempt 1 meets {0}", failure), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 149
      await testRunner.ThenAsync(string.Format("attempt 1 is logged as a \"{0}\" failure", kind), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 150
      await testRunner.AndAsync(string.Format("{0}", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A mail is delivered when the mail server comes back")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AMailIsDeliveredWhenTheMailServerComesBack()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A mail is delivered when the mail server comes back", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A transient failure is retried, at most 3 attempts in all", null, tagsOfRule);
#line 161
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 142
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
      await testRunner.GivenAsync("the mail catcher is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
      await testRunner.AndAsync("\"treasury-ops\" emailed template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
      await testRunner.WhenAsync("the mail catcher starts again before attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 165
      await testRunner.ThenAsync("the mail catcher holds 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 166
      await testRunner.AndAsync("1 transient attempt failure and 1 delivery on attempt 2 are logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A notification fails after 3 transient failures")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ANotificationFailsAfter3TransientFailures()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A notification fails after 3 transient failures", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A transient failure is retried, at most 3 attempts in all", null, tagsOfRule);
#line 169
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 142
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
      await testRunner.GivenAsync("the mail catcher is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 172
      await testRunner.ThenAsync("3 attempts are made, attempt 2 no sooner than 5 seconds after attempt 1, and atte" +
                        "mpt 3 no sooner than 30 seconds after attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 173
      await testRunner.AndAsync("3 attempt failures and 1 failure error with attempt count 3 are logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
      await testRunner.AndAsync("the failed count for \"email\" rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A waiting notification does not hold up the next one")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AWaitingNotificationDoesNotHoldUpTheNextOne()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A waiting notification does not hold up the next one", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A transient failure is retried, at most 3 attempts in all", null, tagsOfRule);
#line 177
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 142
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
      await testRunner.GivenAsync("the mail server answers 451 to the first attempt for \"jane@example.com\" only", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 179
      await testRunner.WhenAsync("\"treasury-ops\" emails \"jane@example.com\" and then \"john@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 180
      await testRunner.ThenAsync("the mail to \"john@example.com\" is delivered before the mail to \"jane@example.com\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 181
      await testRunner.AndAsync("the mail to \"jane@example.com\" is delivered on attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A stop loses a notification that has not ended")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AStopLosesANotificationThatHasNotEnded()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A stop loses a notification that has not ended", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A transient failure is retried, at most 3 attempts in all", null, tagsOfRule);
#line 184
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 142
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
      await testRunner.GivenAsync("the mail catcher is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 186
      await testRunner.AndAsync("\"treasury-ops\" emailed template \"account-opened\" to \"jane@example.com\", and it wa" +
                        "its for attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
      await testRunner.WhenAsync("the service is restarted after the mail catcher is back", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 188
      await testRunner.ThenAsync("the mail catcher receives no mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An SMTP reply text never reaches the logs")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AnSMTPReplyTextNeverReachesTheLogs()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An SMTP reply text never reaches the logs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A transient failure is retried, at most 3 attempts in all", null, tagsOfRule);
#line 191
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 142
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
      await testRunner.GivenAsync("the mail server answers attempt 1 with \"550 5.1.1 <jane@example.com> unknown user" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 193
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 194
      await testRunner.ThenAsync("the attempt failure entry holds the reply code 550", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 195
      await testRunner.AndAsync("no log entry holds \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A repeated call sends 1 mail")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ARepeatedCallSends1Mail()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "29";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A repeated call sends 1 mail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call never sends a second mail", null, tagsOfRule);
#line 204
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 200
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 201
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
      await testRunner.GivenAsync("\"treasury-ops\" emailed template \"account-opened\" to \"jane@example.com\" with key \"" +
                        "k-5001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 206
      await testRunner.WhenAsync("\"treasury-ops\" sends the same call again with key \"k-5001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 207
      await testRunner.ThenAsync("the second answer carries the same notification id as the first", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 208
      await testRunner.AndAsync("the mail catcher holds exactly 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
      await testRunner.AndAsync("exactly 1 queued entry is logged, and the queued and delivered counts for \"email\"" +
                        " each rose by 1 only", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A new token for the same caller still sends 1 mail")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ANewTokenForTheSameCallerStillSends1Mail()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "30";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A new token for the same caller still sends 1 mail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call never sends a second mail", null, tagsOfRule);
#line 212
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 200
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 201
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
      await testRunner.GivenAsync("\"treasury-ops\" emailed template \"account-opened\" to \"jane@example.com\" with key \"" +
                        "k-5002\" on its first token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 214
      await testRunner.WhenAsync("\"treasury-ops\" sends the same call with key \"k-5002\" on a new token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 215
      await testRunner.ThenAsync("the second answer carries the same notification id as the first", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 216
      await testRunner.AndAsync("the mail catcher holds exactly 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2 callers with the same key send 2 mails")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task _2CallersWithTheSameKeySend2Mails()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 callers with the same key send 2 mails", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call never sends a second mail", null, tagsOfRule);
#line 219
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 200
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 201
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
      await testRunner.GivenAsync("\"card-ops\" is also a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 221
      await testRunner.AndAsync("\"treasury-ops\" emailed template \"account-opened\" to \"jane@example.com\" with key \"" +
                        "k-5003\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 222
      await testRunner.WhenAsync("\"card-ops\" emails template \"account-opened\" to \"jane@example.com\" with key \"k-500" +
                        "3\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 223
      await testRunner.ThenAsync("\"card-ops\" gets a different notification id from \"treasury-ops\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 224
      await testRunner.AndAsync("the mail catcher holds 2 mails to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Mail goes over the encryption the settings choose")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("offers STARTTLS, with the security mode STARTTLS set", "STARTTLS", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("speaks TLS from the first byte, with the security mode TLS set", "TLS", "33", null)]
        public async global::System.Threading.Tasks.Task MailGoesOverTheEncryptionTheSettingsChoose(string server, string encryption, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("server", server);
            argumentsOfScenario.Add("encryption", encryption);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mail goes over the encryption the settings choose", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Mail leaves only over an encrypted connection with a checked certificate, signed " +
                    "in as the settings say", null, tagsOfRule);
#line 229
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 230
      await testRunner.GivenAsync(string.Format("the service runs with sign-in on and email set up to send to a mail server that {" +
                            "0}", server), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 231
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 232
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 233
      await testRunner.ThenAsync(string.Format("the mail server holds 1 mail to \"jane@example.com\", received over {0}", encryption), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The service signs in only when the settings name a user")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("offers no sign-in", "no user name", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("accepts only the user \"notify-svc\" with \"Pa55-w0rd-7781\"", "the user \"notify-svc\" and the password \"Pa55-w0rd-7781\"", "35", null)]
        public async global::System.Threading.Tasks.Task TheServiceSignsInOnlyWhenTheSettingsNameAUser(string catcher, string credentials, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("catcher", catcher);
            argumentsOfScenario.Add("credentials", credentials);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The service signs in only when the settings name a user", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Mail leaves only over an encrypted connection with a checked certificate, signed " +
                    "in as the settings say", null, tagsOfRule);
#line 241
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 242
      await testRunner.GivenAsync(string.Format("the service runs with sign-in on and email set up to send to a mail catcher that " +
                            "{0}", catcher), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 243
      await testRunner.AndAsync(string.Format("the SMTP settings hold {0}", credentials), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 244
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 245
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 246
      await testRunner.ThenAsync("the mail catcher holds 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A mail server with a certificate the service does not trust gets no mail")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AMailServerWithACertificateTheServiceDoesNotTrustGetsNoMail()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "36";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A mail server with a certificate the service does not trust gets no mail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Mail leaves only over an encrypted connection with a checked certificate, signed " +
                    "in as the settings say", null, tagsOfRule);
#line 254
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 255
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send to a mail server whose " +
                        "certificate the service does not trust", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 256
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 258
      await testRunner.ThenAsync("the mail server receives no mail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 259
      await testRunner.AndAsync("the notification fails after 3 transient attempt failures", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An SMTP outage does not touch the health check")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AnSMTPOutageDoesNotTouchTheHealthCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "37";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An SMTP outage does not touch the health check", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An SMTP outage does not touch the health check", null, tagsOfRule);
#line 264
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 265
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 266
      await testRunner.AndAsync("the mail catcher is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
      await testRunner.WhenAsync("the cluster\'s liveness probe asks the health check without a token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 268
      await testRunner.ThenAsync("the answer is 200 with the status \"Healthy\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A set-up email sender is logged at start-up")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ASet_UpEmailSenderIsLoggedAtStart_Up()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "38";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A set-up email sender is logged at start-up", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 273
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 274
      await testRunner.GivenAsync("email is on, with the sender \"Smtp\" and every SMTP setting given", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 275
      await testRunner.WhenAsync("the service starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 276
      await testRunner.ThenAsync("1 start-up entry names the email sender \"Smtp\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 277
      await testRunner.AndAsync("no warning says email is not set up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email off logs no email start-up entry")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task EmailOffLogsNoEmailStart_UpEntry()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "39";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email off logs no email start-up entry", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 280
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 281
      await testRunner.GivenAsync("email is off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 282
      await testRunner.WhenAsync("the service starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 283
      await testRunner.ThenAsync("no email start-up entry is logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email on but not set up still lets the service start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no mail server host", "the mail server host", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("no sender address", "the sender address", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender address \"notify.example.com\"", "the sender address", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("the port 70000", "the port", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("the security mode \"None\"", "the security mode", "44", null)]
        [global::NUnit.Framework.TestCaseAttribute("a time limit of 500 seconds", "the time limit", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"SendGrid\"", "the sender choice", "46", null)]
        public async global::System.Threading.Tasks.Task EmailOnButNotSetUpStillLetsTheServiceStart(string fault, string setting, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            argumentsOfScenario.Add("setting", setting);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email on but not set up still lets the service start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 286
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 287
      await testRunner.GivenAsync(string.Format("the service started with email on and {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 288
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 289
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 290
      await testRunner.ThenAsync("the call is accepted and skipped with reason \"ChannelNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 291
      await testRunner.AndAsync(string.Format("the start-up wrote 1 warning that email is not set up, naming {0} and no setting " +
                            "value", setting), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A settings change takes effect only at the next start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ASettingsChangeTakesEffectOnlyAtTheNextStart()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "47";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A settings change takes effect only at the next start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its email settings when it starts", null, tagsOfRule);
#line 304
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 305
      await testRunner.GivenAsync("the service started with email off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 306
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 307
      await testRunner.AndAsync("the email settings are turned on while the service runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 308
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 309
      await testRunner.ThenAsync("the call is accepted and skipped with reason \"ChannelNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A local email shows up in the mail catcher")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ALocalEmailShowsUpInTheMailCatcher()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "48";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A local email shows up in the mail catcher", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The local run shows each mail", null, tagsOfRule);
#line 314
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 315
      await testRunner.GivenAsync("the service runs with the local-run settings: sign-in off and email set up to sen" +
                        "d to the mail catcher over STARTTLS", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 316
      await testRunner.WhenAsync("Minh, a developer, emails template \"account-opened\" to \"jane@example.com\" for cus" +
                        "tomer \"<b>Jane</b>\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 317
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 318
      await testRunner.AndAsync("within 10 seconds Minh can read 1 mail to \"jane@example.com\" in the mail catcher," +
                        " with the subject \"Your account is open\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 319
      await testRunner.AndAsync("the mail shows \"<b>Jane</b>\" as text, not in bold", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
