// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DKNet.Notification.App.BDDTests.Features.Notifications
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Microsoft Graph email sender")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MicrosoftGraphEmailSenderFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Notifications", "Microsoft Graph email sender", "", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GraphEmailSender.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Notifications/GraphEmailSender.feature.ndjson", 63);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An email reaches Graph from the one mailbox")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AnEmailReachesGraphFromTheOneMailbox()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email reaches Graph from the one mailbox", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email is sent through Graph from the one mailbox when the sender is Graph", null, tagsOfRule);
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub from the mailbox \"notify@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
      await testRunner.AndAsync("the Graph stub records 1 send from \"notify@contoso.com\" to \"jane@example.com\" onl" +
                        "y, with the subject \"Your account is open\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
      await testRunner.AndAsync("the send has an HTML body that says \"Dear Jane Tan, your account 0012345678 is op" +
                        "en.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
      await testRunner.AndAsync("the send has no copy recipient, no attachment, no sender address, no sender name " +
                        "and no Sent Items choice", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A caller cannot choose the mailbox")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ACallerCannotChooseTheMailbox()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A caller cannot choose the mailbox", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email is sent through Graph from the one mailbox when the sender is Graph", null, tagsOfRule);
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub from the mailbox \"notify@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" with an ext" +
                        "ra parameter \"from\" set to \"ceo@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
      await testRunner.ThenAsync("the Graph stub records 1 send from \"notify@contoso.com\" to \"jane@example.com\" onl" +
                        "y", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
      await testRunner.AndAsync("no send names \"ceo@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Any 2xx answer from Graph ends Delivered")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 202", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 200", "3", null)]
        public async global::System.Threading.Tasks.Task Any2XxAnswerFromGraphEndsDelivered(string answer, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("answer", answer);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Any 2xx answer from Graph ends Delivered", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email is sent through Graph from the one mailbox when the sender is Graph", null, tagsOfRule);
#line 37
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub from the mailbox \"notify@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
      await testRunner.GivenAsync(string.Format("Graph answers the send with {0}", answer), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
      await testRunner.ThenAsync("1 delivered entry on attempt 1 is logged for the notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Graph delivery is logged and counted")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AGraphDeliveryIsLoggedAndCounted()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Graph delivery is logged and counted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email is sent through Graph from the one mailbox when the sender is Graph", null, tagsOfRule);
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub from the mailbox \"notify@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
      await testRunner.ThenAsync("1 queued entry and 1 delivered entry on attempt 1 are logged for the notification" +
                        " id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
      await testRunner.AndAsync("both entries carry the trace id of the call", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
      await testRunner.AndAsync("the accepted count for \"email\" with outcome \"queued\" and the delivered count for " +
                        "\"email\" each rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
      await testRunner.AndAsync("1 delivery duration is recorded for \"email\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("No personal data, token or secret reaches the logs, traces or kept records")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task NoPersonalDataTokenOrSecretReachesTheLogsTracesOrKeptRecords()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No personal data, token or secret reaches the logs, traces or kept records", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email is sent through Graph from the one mailbox when the sender is Graph", null, tagsOfRule);
#line 56
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub from the mailbox \"notify@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
      await testRunner.GivenAsync("the Graph sender signs in with the client secret \"Gr4ph-s3cret-9921\" at the token" +
                        " stub, which issues the token \"tok-5521-abc\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
      await testRunner.ThenAsync("the Graph stub records 1 send to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
      await testRunner.AndAsync("no log entry, trace or kept idempotency record holds \"jane@example.com\", \"Jane Ta" +
                        "n\", \"0012345678\", \"Gr4ph-s3cret-9921\" or \"tok-5521-abc\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A provider\'s error text never reaches the logs")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("Graph", "400", "Invalid recipient jane@example.com", "jane@example.com", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("the token stub", "400", "Bad request, trace 7f3a-9921", "7f3a-9921", "7", null)]
        public async global::System.Threading.Tasks.Task AProvidersErrorTextNeverReachesTheLogs(string step, string code, string text, string secretPart, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("step", step);
            argumentsOfScenario.Add("code", code);
            argumentsOfScenario.Add("text", text);
            argumentsOfScenario.Add("secret part", secretPart);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A provider\'s error text never reaches the logs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An email is sent through Graph from the one mailbox when the sender is Graph", null, tagsOfRule);
#line 63
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub from the mailbox \"notify@contoso.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
      await testRunner.GivenAsync(string.Format("{0} answers attempt 1 with {1} and the error text \"{2}\"", step, code, text), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
      await testRunner.ThenAsync(string.Format("the attempt failure entry holds the status code {0}", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
      await testRunner.AndAsync(string.Format("no log entry holds \"{0}\"", secretPart), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Only the chosen sender gets the mail")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\"", "the Graph stub", "the mail catcher", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"graph\"", "the Graph stub", "the mail catcher", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Smtp\"", "the mail catcher", "the Graph stub and the token stub", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("no sender given", "the mail catcher", "the Graph stub and the token stub", "11", null)]
        public async global::System.Threading.Tasks.Task OnlyTheChosenSenderGetsTheMail(string senderChoice, string receiver, string idle, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("sender choice", senderChoice);
            argumentsOfScenario.Add("receiver", receiver);
            argumentsOfScenario.Add("idle", idle);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only the chosen sender gets the mail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only the chosen sender is active", null, tagsOfRule);
#line 77
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
      await testRunner.GivenAsync(string.Format("the service runs with sign-in on, email on with {0}, and both the mail catcher an" +
                            "d the Graph stub ready", senderChoice), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
      await testRunner.ThenAsync(string.Format("{0} receives 1 mail to \"jane@example.com\"", receiver), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
      await testRunner.AndAsync(string.Format("{0} receives nothing", idle), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The other sender\'s settings are not read")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("Graph", "no mail server host", "the Graph stub", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("Smtp", "the tenant id \"contoso.onmicrosoft.com\"", "the mail catcher", "13", null)]
        public async global::System.Threading.Tasks.Task TheOtherSendersSettingsAreNotRead(string sender, string otherFault, string receiver, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("sender", sender);
            argumentsOfScenario.Add("other fault", otherFault);
            argumentsOfScenario.Add("receiver", receiver);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The other sender\'s settings are not read", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only the chosen sender is active", null, tagsOfRule);
#line 92
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
      await testRunner.GivenAsync(string.Format("the service started with email on, the sender \"{0}\", every setting of that sender" +
                            " given, and {1}", sender, otherFault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
      await testRunner.ThenAsync(string.Format("1 start-up entry names the email sender \"{0}\"", sender), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
      await testRunner.AndAsync(string.Format("{0} receives 1 mail to \"jane@example.com\"", receiver), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A sender change takes effect only at the next start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ASenderChangeTakesEffectOnlyAtTheNextStart()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A sender change takes effect only at the next start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only the chosen sender is active", null, tagsOfRule);
#line 105
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 106
      await testRunner.GivenAsync("the service started with email on and the sender \"Smtp\", with the mail catcher an" +
                        "d the Graph stub ready", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 107
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
      await testRunner.AndAsync("the sender is changed to \"Graph\" while the service runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
      await testRunner.ThenAsync("the mail catcher receives 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 111
      await testRunner.AndAsync("the Graph stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2 notifications in a row ask for 1 token")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task _2NotificationsInARowAskFor1Token()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 notifications in a row ask for 1 token", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service signs in as the mail-sender app", null, tagsOfRule);
#line 121
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 116
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub, with the delivery waits of 5 seconds and 30 se" +
                        "conds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
      await testRunner.AndAsync("the mail-sender app \"7c1d4e2a-0b9f-4a63-8e15-2d6f9b3c8a41\" signs in with a client" +
                        " secret at the token stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
      await testRunner.WhenAsync("\"treasury-ops\" emails \"jane@example.com\" and then \"john@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
      await testRunner.ThenAsync("the Graph stub records 2 sends, each with the token the token stub issued", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
      await testRunner.AndAsync("the token stub received 1 token request, from the app \"7c1d4e2a-0b9f-4a63-8e15-2d" +
                        "6f9b3c8a41\", for Microsoft Graph", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Each sign-in answer is retried or not by its kind")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 503", "transient", "the status code 503", "the mail is sent on attempt 2, after 2 token requests in all", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 408", "transient", "the status code 408", "the mail is sent on attempt 2, after 2 token requests in all", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 429 with a retry after of 2 seconds", "transient", "the status code 429", "the mail is sent on attempt 2, no sooner than 2 seconds and sooner than 5 seconds" +
            " after attempt 1", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("no answer within the attempt\'s time limit", "transient", "no status code", "the mail is sent on attempt 2", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("a refused connection", "transient", "no status code", "the mail is sent on attempt 2", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("a lost connection", "transient", "no status code", "the mail is sent on attempt 2", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 401 with \"invalid_client\"", "permanent", "the status code 401", "the notification fails with no attempt 2, after 1 token request", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 400 with \"invalid_request\"", "permanent", "the status code 400", "the notification fails with no attempt 2, after 1 token request", "23", null)]
        public async global::System.Threading.Tasks.Task EachSign_InAnswerIsRetriedOrNotByItsKind(string answer, string kind, string code, string outcome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("answer", answer);
            argumentsOfScenario.Add("kind", kind);
            argumentsOfScenario.Add("code", code);
            argumentsOfScenario.Add("outcome", outcome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each sign-in answer is retried or not by its kind", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service signs in as the mail-sender app", null, tagsOfRule);
#line 127
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 116
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub, with the delivery waits of 5 seconds and 30 se" +
                        "conds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
      await testRunner.AndAsync("the mail-sender app \"7c1d4e2a-0b9f-4a63-8e15-2d6f9b3c8a41\" signs in with a client" +
                        " secret at the token stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
      await testRunner.GivenAsync(string.Format("the token stub answers the first token request with {0}", answer), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
      await testRunner.ThenAsync(string.Format("attempt 1 is logged as a \"{0}\" failure with {1}", kind, code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 131
      await testRunner.AndAsync(string.Format("{0}", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Workload identity signs in with the service account token")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task WorkloadIdentitySignsInWithTheServiceAccountToken()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workload identity signs in with the service account token", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Workload identity signs in with the service account token, and fails at once with" +
                    "out it", null, tagsOfRule);
#line 147
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 148
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send through the Graph stub " +
                        "by workload identity, signing in at the token stub with the service account toke" +
                        "n \"sa-token-4417\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
      await testRunner.AndAsync("the Graph settings also hold the client secret \"Gr4ph-s3cret-9921\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 150
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 152
      await testRunner.ThenAsync("the token stub received 1 token request that carries \"sa-token-4417\" and not \"Gr4" +
                        "ph-s3cret-9921\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 153
      await testRunner.AndAsync("the Graph stub records 1 send to \"jane@example.com\", and no log entry holds \"sa-t" +
                        "oken-4417\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Workload identity with no service account token fails at once")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task WorkloadIdentityWithNoServiceAccountTokenFailsAtOnce()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workload identity with no service account token fails at once", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Workload identity signs in with the service account token, and fails at once with" +
                    "out it", null, tagsOfRule);
#line 156
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 157
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send through the Graph stub " +
                        "by workload identity, with no service account token given to it", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 160
      await testRunner.ThenAsync("attempt 1 is logged as a \"permanent\" failure with no status code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 161
      await testRunner.AndAsync("the notification fails with no attempt 2, and the Graph stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Each Graph answer is retried or not by its kind")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 503", "transient", "the status code 503", "the mail is sent on attempt 2, no sooner than 5 seconds after attempt 1", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 408", "transient", "the status code 408", "the mail is sent on attempt 2", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("a refused connection", "transient", "no status code", "the mail is sent on attempt 2", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("a lost connection", "transient", "no status code", "the mail is sent on attempt 2", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("a send it records but answers only after the attempt\'s time limit", "transient", "no status code", "the mail is sent on attempt 2, and the Graph stub holds 2 sends to \"jane@example." +
            "com\"", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("a slow token and a slow send that together pass the attempt\'s time limit", "transient", "no status code", "the mail is sent on attempt 2", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 400", "permanent", "the status code 400", "the notification fails with no attempt 2", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 401", "permanent", "the status code 401", "the notification fails with no attempt 2", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 403", "permanent", "the status code 403", "the notification fails with no attempt 2", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 404", "permanent", "the status code 404", "the notification fails with no attempt 2", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 302 to \"https://elsewhere.example\"", "permanent", "the status code 302", "the notification fails with no attempt 2, and \"https://elsewhere.example\" receive" +
            "s nothing", "36", null)]
        public async global::System.Threading.Tasks.Task EachGraphAnswerIsRetriedOrNotByItsKind(string answer, string kind, string code, string outcome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("answer", answer);
            argumentsOfScenario.Add("kind", kind);
            argumentsOfScenario.Add("code", code);
            argumentsOfScenario.Add("outcome", outcome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each Graph answer is retried or not by its kind", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Graph answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 170
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 166
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub, with the delivery waits of 5 seconds and 30 se" +
                        "conds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 167
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
      await testRunner.GivenAsync(string.Format("Graph answers attempt 1 with {0}", answer), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 172
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
      await testRunner.ThenAsync(string.Format("attempt 1 is logged as a \"{0}\" failure with {1}", kind, code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 174
      await testRunner.AndAsync(string.Format("{0}", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A notification fails after 3 transient Graph answers")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ANotificationFailsAfter3TransientGraphAnswers()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "37";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A notification fails after 3 transient Graph answers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Graph answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 191
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 166
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub, with the delivery waits of 5 seconds and 30 se" +
                        "conds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 167
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
      await testRunner.GivenAsync("Graph answers 503 to every send", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 193
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 194
      await testRunner.ThenAsync("3 attempts are made, with 3 sends in all", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 195
      await testRunner.AndAsync("3 attempt failures and 1 failure error with attempt count 3 are logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
      await testRunner.AndAsync("the failed count for \"email\" rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The wait after a 429 follows the retry-after header")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("a retry after of 2 seconds", "no sooner than 2 seconds and sooner than 5 seconds after attempt 1", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("a retry after of 0 seconds", "sooner than 5 seconds after attempt 1", "39", null)]
        [global::NUnit.Framework.TestCaseAttribute("a retry-after date 3 seconds from now", "no sooner than 2 seconds and sooner than 5 seconds after attempt 1", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("a retry-after date in the past", "sooner than 5 seconds after attempt 1", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("no retry-after header", "no sooner than 5 seconds after attempt 1", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("the retry-after value \"soon\"", "no sooner than 5 seconds after attempt 1", "43", null)]
        public async global::System.Threading.Tasks.Task TheWaitAfterA429FollowsTheRetry_AfterHeader(string header, string timing, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("header", header);
            argumentsOfScenario.Add("timing", timing);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The wait after a 429 follows the retry-after header", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("After a 429 the next attempt waits the time Graph asks, at most 60 seconds", null, tagsOfRule);
#line 205
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 201
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub, with the delivery waits of 5 seconds and 30 se" +
                        "conds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 202
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
      await testRunner.GivenAsync(string.Format("Graph answers attempt 1 with 429 and {0}", header), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 207
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 208
      await testRunner.ThenAsync(string.Format("the mail is sent on attempt 2, {0}", timing), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A notification waiting after a 429 does not hold up the next one")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ANotificationWaitingAfterA429DoesNotHoldUpTheNextOne()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "44";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A notification waiting after a 429 does not hold up the next one", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("After a 429 the next attempt waits the time Graph asks, at most 60 seconds", null, tagsOfRule);
#line 220
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 201
      await testRunner.GivenAsync("the service runs with its released template catalogue, sign-in on and email set u" +
                        "p to send through the Graph stub, with the delivery waits of 5 seconds and 30 se" +
                        "conds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 202
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 221
      await testRunner.GivenAsync("Graph answers the first send for \"jane@example.com\" with 429 and a retry after of" +
                        " 10 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 222
      await testRunner.WhenAsync("\"treasury-ops\" emails \"jane@example.com\" and then \"john@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 223
      await testRunner.ThenAsync("the mail to \"john@example.com\" is sent before the mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 224
      await testRunner.AndAsync("the mail to \"jane@example.com\" is sent on attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A set-up Graph sender is logged at start-up")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"WorkloadIdentity\" and no client secret", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"workloadidentity\" and no client secret", "46", null)]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"WorkloadIdentity\" and a client secret of 513 characters", "47", null)]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"ClientSecret\" and a client secret", "48", null)]
        public async global::System.Threading.Tasks.Task ASet_UpGraphSenderIsLoggedAtStart_Up(string credential, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("credential", credential);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A set-up Graph sender is logged at start-up", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Graph settings when it starts", null, tagsOfRule);
#line 229
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 230
      await testRunner.GivenAsync(string.Format("email is on, with the sender \"Graph\", every Graph setting given and {0}", credential), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 231
      await testRunner.WhenAsync("the service starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 232
      await testRunner.ThenAsync("1 start-up entry names the email sender \"Graph\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 233
      await testRunner.AndAsync("no warning says email is not set up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email on but not set up for Graph still lets the service start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and no mailbox", "the mailbox", "49", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the mailbox \"notify.contoso.com\"", "the mailbox", "50", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and a mailbox of 255 characters", "the mailbox", "51", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the mailbox \"notify@contoso.com, ops@contoso.com\"", "the mailbox", "52", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and no tenant id", "the tenant id", "53", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the tenant id \"contoso.onmicrosoft.com\"", "the tenant id", "54", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the client id \"mail-sender\"", "the client id", "55", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the credential mode \"Certificate\"", "the credential mode", "56", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\", the credential mode \"ClientSecret\" and no client secret", "the client secret", "57", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\", the credential mode \"ClientSecret\" and a client secret of 513" +
            " characters", "the client secret", "58", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"SendGrid\"", "the sender choice", "59", null)]
        public async global::System.Threading.Tasks.Task EmailOnButNotSetUpForGraphStillLetsTheServiceStart(string fault, string setting, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            argumentsOfScenario.Add("setting", setting);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email on but not set up for Graph still lets the service start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Graph settings when it starts", null, tagsOfRule);
#line 243
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 244
      await testRunner.GivenAsync(string.Format("the service started with email on and {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 245
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 246
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 247
      await testRunner.ThenAsync("the call is accepted and skipped with reason \"ChannelNotConfigured\", and the Grap" +
                        "h stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 248
      await testRunner.AndAsync(string.Format("the start-up wrote 1 warning that email is not set up, naming {0} and no setting " +
                            "value", setting), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Graph outage does not touch the health check")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AGraphOutageDoesNotTouchTheHealthCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "60";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Graph outage does not touch the health check", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Graph outage does not touch the health check", null, tagsOfRule);
#line 267
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 268
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send through the Graph stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 269
      await testRunner.AndAsync("the Graph stub and the token stub are stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 270
      await testRunner.WhenAsync("the cluster\'s liveness probe asks the health check without a token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 271
      await testRunner.ThenAsync("the answer is 200 with the status \"Healthy\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
