// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DKNet.Notification.App.BDDTests.Features.Notifications
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Microsoft Graph email sender")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MicrosoftGraphEmailSenderFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Notifications", "Microsoft Graph email sender", "", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GraphEmailSender.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Notifications/GraphEmailSender.feature.ndjson", 19);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A sender change takes effect only at the next start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ASenderChangeTakesEffectOnlyAtTheNextStart()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A sender change takes effect only at the next start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only the chosen sender is active", null, tagsOfRule);
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service started with email on and the sender \"Smtp\", with the mail catcher an" +
                        "d the Graph stub ready", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("the sender is changed to \"Graph\" while the service runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
      await testRunner.ThenAsync("the mail catcher receives 1 mail to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
      await testRunner.AndAsync("the Graph stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A set-up Graph sender is logged at start-up")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"WorkloadIdentity\" and no client secret", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"workloadidentity\" and no client secret", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"WorkloadIdentity\" and a client secret of 513 characters", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("the credential mode \"ClientSecret\" and a client secret", "4", null)]
        public async global::System.Threading.Tasks.Task ASet_UpGraphSenderIsLoggedAtStart_Up(string credential, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("credential", credential);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A set-up Graph sender is logged at start-up", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Graph settings when it starts", null, tagsOfRule);
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
      await testRunner.GivenAsync(string.Format("email is on, with the sender \"Graph\", every Graph setting given and {0}", credential), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
      await testRunner.WhenAsync("the service starts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
      await testRunner.ThenAsync("1 start-up entry names the email sender \"Graph\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
      await testRunner.AndAsync("no warning says email is not set up", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email on but not set up for Graph still lets the service start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and no mailbox", "the mailbox", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the mailbox \"notify.contoso.com\"", "the mailbox", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and a mailbox of 255 characters", "the mailbox", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the mailbox \"notify@contoso.com, ops@contoso.com\"", "the mailbox", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and no tenant id", "the tenant id", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the tenant id \"contoso.onmicrosoft.com\"", "the tenant id", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the client id \"mail-sender\"", "the client id", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\" and the credential mode \"Certificate\"", "the credential mode", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\", the credential mode \"ClientSecret\" and no client secret", "the client secret", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"Graph\", the credential mode \"ClientSecret\" and a client secret of 513" +
            " characters", "the client secret", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("the sender \"SendGrid\"", "the sender choice", "15", null)]
        public async global::System.Threading.Tasks.Task EmailOnButNotSetUpForGraphStillLetsTheServiceStart(string fault, string setting, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            argumentsOfScenario.Add("setting", setting);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email on but not set up for Graph still lets the service start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Graph settings when it starts", null, tagsOfRule);
#line 42
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
      await testRunner.GivenAsync(string.Format("the service started with email on and {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
      await testRunner.ThenAsync("the call is accepted and skipped with reason \"ChannelNotConfigured\", and the Grap" +
                        "h stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
      await testRunner.AndAsync(string.Format("the start-up wrote 1 warning that email is not set up, naming {0} and no setting " +
                            "value", setting), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Graph outage does not touch the health check")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AGraphOutageDoesNotTouchTheHealthCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Graph outage does not touch the health check", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Graph outage does not touch the health check", null, tagsOfRule);
#line 66
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
      await testRunner.GivenAsync("the service runs with sign-in on and email set up to send through the Graph stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
      await testRunner.AndAsync("the Graph stub and the token stub are stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
      await testRunner.WhenAsync("the cluster\'s liveness probe asks the health check without a token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
      await testRunner.ThenAsync("the answer is 200 with the status \"Healthy\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
