// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DKNet.Notification.App.BDDTests.Features.Notifications
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Send API: the send endpoint, sign-in, idempotency and skip")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SendAPITheSendEndpointSign_InIdempotencyAndSkipFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Notifications", "Send API: the send endpoint, sign-in, idempotency and skip", "", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "SendNotification.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Notifications/SendNotification.feature.ndjson", 43);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A valid email call is accepted and skipped")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AValidEmailCallIsAcceptedAndSkipped()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A valid email call is accepted and skipped", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid call is accepted, logged and skipped", null, tagsOfRule);
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
      await testRunner.WhenAsync("\"treasury-ops\" asks to email template \"account-opened\" to \"jane@example.com\" with" +
                        " key \"k-1001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
      await testRunner.AndAsync("exactly 1 skip warning is logged with reason \"ChannelNotConfigured\" and caller \"t" +
                        "reasury-ops\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Every channel is skipped in this release")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("email", "email", "ChannelNotConfigured", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("Teams", "teams", "ChannelNotConfigured", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("whatsapp", "whatsapp", "ChannelNotSupported", "3", null)]
        public async global::System.Threading.Tasks.Task EveryChannelIsSkippedInThisRelease(string sent, string logged, string reason, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("sent", sent);
            argumentsOfScenario.Add("logged", logged);
            argumentsOfScenario.Add("reason", reason);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Every channel is skipped in this release", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid call is accepted, logged and skipped", null, tagsOfRule);
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" sends template \"account-opened\" on channel \"{0}\"", sent), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
      await testRunner.AndAsync(string.Format("the skip warning names channel \"{0}\" and reason \"{1}\"", logged, reason), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An email call with an empty parameter list is still skipped in this release")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AnEmailCallWithAnEmptyParameterListIsStillSkippedInThisRelease()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email call with an empty parameter list is still skipped in this release", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid call is accepted, logged and skipped", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
      await testRunner.WhenAsync("\"treasury-ops\" sends template \"account-opened\" on channel \"email\" with an empty p" +
                        "arameter list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
      await testRunner.AndAsync("the skip warning names reason \"ChannelNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("No personal data reaches the logs")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task NoPersonalDataReachesTheLogs()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No personal data reaches the logs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid call is accepted, logged and skipped", null, tagsOfRule);
#line 45
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\" for custome" +
                        "r \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
      await testRunner.ThenAsync("no log entry holds \"jane@example.com\", \"Jane Tan\" or \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The permission is read from any of its 3 claims")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("scp", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("scope", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("roles", "8", null)]
        public async global::System.Threading.Tasks.Task ThePermissionIsReadFromAnyOfIts3Claims(string claim, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("claim", claim);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The permission is read from any of its 3 claims", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only a signed-in caller with the permission may send", null, tagsOfRule);
#line 55
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
      await testRunner.GivenAsync(string.Format("\"card-ops\" holds a token with \"notifications.send\" in its \"{0}\" claim", claim), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
      await testRunner.WhenAsync("\"card-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A caller without a good token is refused before anything else")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no token", "401", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("an invalid token", "401", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("a token that names no calling application", "401", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("a token without the permission", "403", "12", null)]
        public async global::System.Threading.Tasks.Task ACallerWithoutAGoodTokenIsRefusedBeforeAnythingElse(string credential, string status, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("credential", credential);
            argumentsOfScenario.Add("status", status);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A caller without a good token is refused before anything else", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only a signed-in caller with the permission may send", null, tagsOfRule);
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
      await testRunner.GivenAsync(string.Format("\"card-ops\" calls with {0}", credential), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
      await testRunner.WhenAsync("\"card-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
      await testRunner.ThenAsync(string.Format("the call is refused with status {0} and an empty body", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
      await testRunner.AndAsync("no skip warning is logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The caller id comes from the first caller claim")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("client_id", "treasury-ops", "azp", "console-app", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("client_id", "treasury-ops", "appid", "legacy-app", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("azp", "console-app", "appid", "legacy-app", "15", null)]
        public async global::System.Threading.Tasks.Task TheCallerIdComesFromTheFirstCallerClaim(string firstClaim, string first, string secondClaim, string second, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("first claim", firstClaim);
            argumentsOfScenario.Add("first", first);
            argumentsOfScenario.Add("second claim", secondClaim);
            argumentsOfScenario.Add("second", second);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The caller id comes from the first caller claim", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only a signed-in caller with the permission may send", null, tagsOfRule);
#line 81
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 82
      await testRunner.GivenAsync(string.Format("\"treasury-ops\" holds a token with the permission, \"{0}\" in its \"{1}\" claim and \"{" +
                            "2}\" in its \"{3}\" claim", first, firstClaim, second, secondClaim), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 83
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
      await testRunner.ThenAsync(string.Format("the skip warning names caller \"{0}\"", first), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A local run without sign-in shows the skip")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ALocalRunWithoutSign_InShowsTheSkip()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A local run without sign-in shows the skip", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A local run without sign-in uses the caller \"System\"", null, tagsOfRule);
#line 95
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
      await testRunner.GivenAsync("a developer runs the service locally with its released template catalogue and sig" +
                        "n-in off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
      await testRunner.WhenAsync("the developer emails template \"account-opened\" to \"jane@example.com\" with key \"k-" +
                        "3001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 99
      await testRunner.AndAsync("the skip warning names caller \"System\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A repeated call is answered with the first answer")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ARepeatedCallIsAnsweredWithTheFirstAnswer()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A repeated call is answered with the first answer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 108
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
      await testRunner.GivenAsync("\"treasury-ops\" emailed template \"account-opened\" to \"jane@example.com\" with key \"" +
                        "k-1002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 110
      await testRunner.WhenAsync("\"treasury-ops\" sends the same call again with key \"k-1002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
      await testRunner.ThenAsync("the second answer carries the same notification id as the first", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 112
      await testRunner.AndAsync("exactly 1 skip warning is logged, and the accepted count rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A new token for the same caller keeps the replay")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ANewTokenForTheSameCallerKeepsTheReplay()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A new token for the same caller keeps the replay", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 115
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
      await testRunner.GivenAsync("\"treasury-ops\" emailed template \"account-opened\" with key \"k-1003\" on its first t" +
                        "oken", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
      await testRunner.WhenAsync("\"treasury-ops\" sends the same call with key \"k-1003\" on a new token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
      await testRunner.ThenAsync("the second answer carries the same notification id as the first", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 119
      await testRunner.AndAsync("exactly 1 skip warning is logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2 callers can use the same key")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task _2CallersCanUseTheSameKey()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 callers can use the same key", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 122
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
      await testRunner.GivenAsync("\"card-ops\" is also a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 124
      await testRunner.AndAsync("\"treasury-ops\" emailed template \"account-opened\" with key \"k-2001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
      await testRunner.WhenAsync("\"card-ops\" emails template \"account-opened\" with key \"k-2001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 126
      await testRunner.ThenAsync("\"card-ops\" gets a different notification id from \"treasury-ops\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 127
      await testRunner.AndAsync("2 skip warnings are logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A key is held for 30 seconds after a refused call")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("k-4001", "5 seconds", "is refused with status 409", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("k-4002", "31 seconds", "is accepted with a new notification id", "21", null)]
        public async global::System.Threading.Tasks.Task AKeyIsHeldFor30SecondsAfterARefusedCall(string key, string wait, string result, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("key", key);
            argumentsOfScenario.Add("wait", wait);
            argumentsOfScenario.Add("result", result);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A key is held for 30 seconds after a refused call", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 130
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
      await testRunner.GivenAsync(string.Format("\"treasury-ops\" sent template \"account-closed\" with key \"{0}\" and was refused with" +
                            " \"TEMPLATE_NOT_FOUND\"", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 132
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" sends template \"account-opened\" with key \"{0}\" {1} later", key, wait), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
      await testRunner.ThenAsync(string.Format("the second call {0}", result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A call refused for its body holds no key")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("a call with an empty channel", "k-4004", "\"INVALID_REQUEST\"", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("a call whose body is 65,537 bytes", "k-4005", "status 413", "23", null)]
        public async global::System.Threading.Tasks.Task ACallRefusedForItsBodyHoldsNoKey(string refusedCall, string key, string refusal, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("refused call", refusedCall);
            argumentsOfScenario.Add("key", key);
            argumentsOfScenario.Add("refusal", refusal);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A call refused for its body holds no key", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 141
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
      await testRunner.GivenAsync(string.Format("\"treasury-ops\" sent {0} and key \"{1}\" and was refused with {2}", refusedCall, key, refusal), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"account-opened\" with key \"{0}\" at once", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 144
      await testRunner.ThenAsync("the second call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A repeat of a call that is still running is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ARepeatOfACallThatIsStillRunningIsRefused()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A repeat of a call that is still running is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 152
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
      await testRunner.GivenAsync("\"treasury-ops\" emailed template \"account-opened\" with key \"k-4003\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 154
      await testRunner.AndAsync("the service is still working on that call", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
      await testRunner.WhenAsync("\"treasury-ops\" sends the same call again with key \"k-4003\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 156
      await testRunner.ThenAsync("the second call is refused with status 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A bad idempotency key is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no key", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("a key of 256 characters", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("the key \"k 1001\"", "27", null)]
        public async global::System.Threading.Tasks.Task ABadIdempotencyKeyIsRefused(string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A bad idempotency key is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A repeated call is never processed twice", null, tagsOfRule);
#line 159
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"account-opened\" with {0}", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 161
      await testRunner.ThenAsync("the call is refused with status 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 162
      await testRunner.AndAsync("no skip warning is logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A body larger than 64 KB is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ABodyLargerThan64KBIsRefused()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A body larger than 64 KB is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The body and the template are checked before the skip", null, tagsOfRule);
#line 177
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 173
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 174
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
      await testRunner.WhenAsync("\"treasury-ops\" sends a call whose body is 65,537 bytes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
      await testRunner.ThenAsync("the call is refused with status 413", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A body that breaks a field rule is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("an empty channel", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("a channel of 51 characters", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("a template id of 101 characters", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("no parameter list at all", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("the parameter \"amount\" set to the number 100", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("51 parameters", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("the parameter \"customer-name\"", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("a parameter value of 4,001 characters", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("a body that is not JSON", "37", null)]
        public async global::System.Threading.Tasks.Task ABodyThatBreaksAFieldRuleIsRefused(string fault, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A body that breaks a field rule is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The body and the template are checked before the skip", null, tagsOfRule);
#line 182
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 173
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 174
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" sends a call with {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 184
      await testRunner.ThenAsync("the call is refused with \"INVALID_REQUEST\" and a trace id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 185
      await testRunner.AndAsync("1 rejection entry is logged with \"INVALID_REQUEST\", and the rejected count for it" +
                        " rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An unknown template is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("account-closed", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("Account-Opened", "39", null)]
        public async global::System.Threading.Tasks.Task AnUnknownTemplateIsRefused(string template, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("template", template);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown template is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The body and the template are checked before the skip", null, tagsOfRule);
#line 200
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 173
      await testRunner.GivenAsync("the service runs with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 174
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 201
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" emails template \"{0}\" to \"jane@example.com\"", template), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 202
      await testRunner.ThenAsync("the call is refused with \"TEMPLATE_NOT_FOUND\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 203
      await testRunner.AndAsync(string.Format("1 rejection entry is logged with \"TEMPLATE_NOT_FOUND\" and template \"{0}\"", template), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The catalogue does not change while the service runs")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task TheCatalogueDoesNotChangeWhileTheServiceRuns()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "40";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The catalogue does not change while the service runs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its set-up when it starts, and its health check stays quiet", null, tagsOfRule);
#line 213
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 214
      await testRunner.GivenAsync("the service started with its released template catalogue and sign-in on", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 215
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
      await testRunner.AndAsync("the template settings are changed to remove \"account-opened\" while the service ru" +
                        "ns", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 217
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 218
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
