// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DKNet.Notification.App.BDDTests.Features.Notifications
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Microsoft Teams channel")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MicrosoftTeamsChannelFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Notifications", "Microsoft Teams channel", "", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "TeamsChannel.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Notifications/TeamsChannel.feature.ndjson", 58);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A card reaches the Teams destination")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ACardReachesTheTeamsDestination()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A card reaches the Teams destination", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
      await testRunner.AndAsync("the webhook stub records 1 post: a message with 1 Adaptive Card", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
      await testRunner.AndAsync("the card holds the title \"Account 0012345678 opened\" and the Markdown text \"**Jan" +
                        "e Tan** opened account 0012345678.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
      await testRunner.AndAsync("both text blocks wrap, and the mail catcher receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Teams delivery is logged and counted")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ATeamsDeliveryIsLoggedAndCounted()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Teams delivery is logged and counted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
      await testRunner.ThenAsync("1 queued entry and 1 delivered entry on attempt 1 are logged for the notification" +
                        " id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
      await testRunner.AndAsync("both entries carry the trace id of the call", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
      await testRunner.AndAsync("the accepted count for \"teams\" with outcome \"queued\" and the delivered count for " +
                        "\"teams\" each rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
      await testRunner.AndAsync("1 delivery duration is recorded for \"teams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Any 2xx answer from the webhook ends Delivered")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 202", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 200", "3", null)]
        public async global::System.Threading.Tasks.Task Any2XxAnswerFromTheWebhookEndsDelivered(string answer, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("answer", answer);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Any 2xx answer from the webhook ends Delivered", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
      await testRunner.GivenAsync(string.Format("the webhook answers the post with {0}", answer), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
      await testRunner.ThenAsync("1 delivered entry on attempt 1 is logged for the notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The channel name is matched without case")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task TheChannelNameIsMatchedWithoutCase()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The channel name is matched without case", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 50
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" on channel \"Teams\" to the Te" +
                        "ams destination \"ops-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
      await testRunner.ThenAsync("the webhook stub records 1 post", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
      await testRunner.AndAsync("the queued entry names the channel \"teams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A value stays text and cannot change the card")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AValueStaysTextAndCannotChangeTheCard()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A value stays text and cannot change the card", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 56
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"\\\"}]},{\\\"type\\\":\\\"Image\\\"\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
      await testRunner.ThenAsync("the webhook stub records 1 post with exactly 1 Adaptive Card of 2 text blocks", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
      await testRunner.AndAsync("the Markdown text holds the customer value exactly as sent", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Markdown in a value reaches the card unchanged")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task MarkdownInAValueReachesTheCardUnchanged()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Markdown in a value reaches the card unchanged", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 62
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"[Jane](https://example.com)\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
      await testRunner.ThenAsync("the card\'s Markdown text is \"**[Jane](https://example.com)** opened account 00123" +
                        "45678.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Teams delivers while email is off")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task TeamsDeliversWhileEmailIsOff()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Teams delivers while email is off", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A valid Teams call posts one card to the named destination", null, tagsOfRule);
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version with the title \"Account {" +
                        "{accountNumber}} opened\" and the body \"**{{customerName}}** opened account {{acc" +
                        "ountNumber}}.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
      await testRunner.GivenAsync("email is off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
      await testRunner.ThenAsync("the webhook stub records 1 post", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The title block follows the filled title")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no title", "with no other value", "no title block", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("the title \"{{headline}}\"", "with headline \"\"", "no title block", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("the title \"{{headline}}\"", "with a headline of 500 characters", "the title of all 500 characters", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("the title \"{{headline}}\"", "with a headline of 501 characters", "the first 500 characters as title", "11", null)]
        public async global::System.Threading.Tasks.Task TheTitleBlockFollowsTheFilledTitle(string title, string extra, string titleBlock, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("title", title);
            argumentsOfScenario.Add("extra", extra);
            argumentsOfScenario.Add("title block", titleBlock);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The title block follows the filled title", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The card has a title block only when there is a title", null, tagsOfRule);
#line 75
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 76
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
      await testRunner.AndAsync(string.Format("the template \"staff-note\" has a Teams version with {0} and the body \"Note for {{{" +
                            "{team}}}}.\"", title), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" posts template \"staff-note\" to the Teams destination \"ops-alerts\" " +
                            "for team \"Treasury\" {0}", extra), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
      await testRunner.ThenAsync(string.Format("the posted card holds {0} and the Markdown text \"Note for Treasury.\"", titleBlock), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A bad destination name is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("with no Teams destination", "RECIPIENT_MISSING", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("to the Teams destination \"\"", "RECIPIENT_MISSING", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("to the Teams destination \"Ops-Alerts\"", "RECIPIENT_INVALID", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("to the Teams destination \"ops alerts\"", "RECIPIENT_INVALID", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("to the Teams destination \" ops-alerts\"", "RECIPIENT_INVALID", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("to the Teams destination \"ops_alerts\"", "RECIPIENT_INVALID", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("to a Teams destination name of 65 characters", "RECIPIENT_INVALID", "18", null)]
        public async global::System.Threading.Tasks.Task ABadDestinationNameIsRefused(string destination, string code, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("destination", destination);
            argumentsOfScenario.Add("code", code);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A bad destination name is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Teams call is checked before it is queued", null, tagsOfRule);
#line 97
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" posts template \"staff-account-opened\" {0}", destination), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
      await testRunner.ThenAsync(string.Format("the call is refused with \"{0}\" naming the Teams destination", code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
      await testRunner.AndAsync("nothing is queued, and the webhook stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A destination that is not set is skipped")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ADestinationThatIsNotSetIsSkipped()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A destination that is not set is skipped", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Teams call is checked before it is queued", null, tagsOfRule);
#line 113
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"fi" +
                        "nance\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
      await testRunner.AndAsync("1 skip warning is logged with reason \"TeamsDestinationNotConfigured\", and it does" +
                        " not hold \"finance\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
      await testRunner.AndAsync("the webhook stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A missing parameter is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AMissingParameterIsRefused()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A missing parameter is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Teams call is checked before it is queued", null, tagsOfRule);
#line 120
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"Jane Tan\" with no account", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
      await testRunner.ThenAsync("the call is refused with \"PARAMETER_MISSING\" naming the parameter \"accountNumber\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
      await testRunner.AndAsync("nothing is queued", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A posted message above 28,672 bytes is refused")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("28,672", "the call is accepted, and the webhook stub records 1 post of 28,672 bytes", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("28,673", "the call is refused with \"MESSAGE_TOO_LARGE\" naming no field, and nothing is queu" +
            "ed", "22", null)]
        public async global::System.Threading.Tasks.Task APostedMessageAbove28672BytesIsRefused(string size, string outcome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("size", size);
            argumentsOfScenario.Add("outcome", outcome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A posted message above 28,672 bytes is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Teams call is checked before it is queued", null, tagsOfRule);
#line 126
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 92
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
      await testRunner.GivenAsync("the template \"staff-digest\" has a Teams version whose body holds the 8 tokens \"{{" +
                        "part1}}\" to \"{{part8}}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" posts template \"staff-digest\" to the Teams destination \"ops-alerts" +
                            "\" with plain-text values that make the posted message {0} bytes", size), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
      await testRunner.ThenAsync(string.Format("{0}", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The skip reason names why")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("the released settings", "account-opened", "teams", "teams", "ChannelNotConfigured", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("Teams on, with \"ops-alerts\" set, and a Teams template", "account-opened", "teams", "teams", "NoTemplateVersion", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("Teams on with no destination, and a Teams template", "staff-account-opened", "teams", "teams", "TeamsDestinationNotConfigured", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("Teams on, with \"ops-alerts\" set, and a Teams template", "staff-account-opened", "whatsapp", "whatsapp", "ChannelNotSupported", "26", null)]
        public async global::System.Threading.Tasks.Task TheSkipReasonNamesWhy(string set_Up, string template, string channel, string logged, string reason, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("set-up", set_Up);
            argumentsOfScenario.Add("template", template);
            argumentsOfScenario.Add("channel", channel);
            argumentsOfScenario.Add("logged", logged);
            argumentsOfScenario.Add("reason", reason);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The skip reason names why", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Teams call is skipped when Teams or the template cannot serve it", null, tagsOfRule);
#line 139
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 140
      await testRunner.GivenAsync(string.Format("the service runs with sign-in on and {0}", set_Up), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 141
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
      await testRunner.WhenAsync(string.Format("\"treasury-ops\" sends template \"{0}\" on channel \"{1}\" to the Teams destination \"op" +
                            "s-alerts\"", template, channel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 143
      await testRunner.ThenAsync("the call is accepted with a new notification id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 144
      await testRunner.AndAsync(string.Format("the skip warning names channel \"{0}\" and reason \"{1}\", and the webhook stub recei" +
                            "ves nothing", logged, reason), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Each webhook answer is retried or not by its kind")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 503", "transient", "the status code 503", "the card is posted on attempt 2, no sooner than 5 seconds after attempt 1", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 408", "transient", "the status code 408", "the card is posted on attempt 2", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 429 with a retry after of 2 seconds", "transient", "the status code 429", "the card is posted on attempt 2, no sooner than 2 seconds and sooner than 5 secon" +
            "ds after attempt 1", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 429 with no retry-after header", "transient", "the status code 429", "the card is posted on attempt 2, no sooner than 5 seconds after attempt 1", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("a refused connection", "transient", "no status code", "the card is posted on attempt 2", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("a lost connection", "transient", "no status code", "the card is posted on attempt 2", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("a post it records but answers only after the Teams time limit", "transient", "no status code", "the card is posted on attempt 2, and the webhook stub holds 2 posts", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 400", "permanent", "the status code 400", "the notification fails with no attempt 2", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 404", "permanent", "the status code 404", "the notification fails with no attempt 2", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("HTTP 302 to \"https://elsewhere.example\"", "permanent", "the status code 302", "the notification fails with no attempt 2, and \"https://elsewhere.example\" receive" +
            "s nothing", "36", null)]
        public async global::System.Threading.Tasks.Task EachWebhookAnswerIsRetriedOrNotByItsKind(string answer, string kind, string code, string outcome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("answer", answer);
            argumentsOfScenario.Add("kind", kind);
            argumentsOfScenario.Add("code", code);
            argumentsOfScenario.Add("outcome", outcome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each webhook answer is retried or not by its kind", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Webhook answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 161
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub, and the delivery waits of 5 seconds and 30 seconds" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
      await testRunner.GivenAsync(string.Format("the webhook answers attempt 1 with {0}", answer), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
      await testRunner.ThenAsync(string.Format("attempt 1 is logged as a \"{0}\" failure with {1}", kind, code), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 165
      await testRunner.AndAsync(string.Format("{0}", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A notification fails after 3 transient webhook answers")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ANotificationFailsAfter3TransientWebhookAnswers()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "37";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A notification fails after 3 transient webhook answers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Webhook answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 181
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub, and the delivery waits of 5 seconds and 30 seconds" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
      await testRunner.GivenAsync("the webhook answers 503 to every post", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 183
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 184
      await testRunner.ThenAsync("3 attempts are made, with 3 posts in all", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 185
      await testRunner.AndAsync("3 attempt failures and 1 failure error with attempt count 3 are logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
      await testRunner.AndAsync("the failed count for \"teams\" rose by 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The Teams time limit is Teams\' own")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task TheTeamsTimeLimitIsTeamsOwn()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "38";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The Teams time limit is Teams\' own", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Webhook answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 189
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub, and the delivery waits of 5 seconds and 30 seconds" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
      await testRunner.GivenAsync("the Teams time limit is 2 seconds and the email time limit is 30 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 191
      await testRunner.AndAsync("the webhook answers attempt 1 only after 3 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 193
      await testRunner.ThenAsync("attempt 1 is logged as a \"transient\" failure with no status code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 194
      await testRunner.AndAsync("the card is posted on attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A webhook whose certificate fails the check gets no card")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AWebhookWhoseCertificateFailsTheCheckGetsNoCard()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "39";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A webhook whose certificate fails the check gets no card", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Webhook answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 197
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub, and the delivery waits of 5 seconds and 30 seconds" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
      await testRunner.GivenAsync("the destination \"ops-alerts\" answers with a certificate the service does not trus" +
                        "t", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 199
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 200
      await testRunner.ThenAsync("attempt 1 is logged as a \"transient\" failure with no status code", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 201
      await testRunner.AndAsync("the webhook stub records no post", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Email and Teams share the places of the queue")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task EmailAndTeamsShareThePlacesOfTheQueue()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "40";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Email and Teams share the places of the queue", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Webhook answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 204
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub, and the delivery waits of 5 seconds and 30 seconds" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
      await testRunner.GivenAsync("the delivery queue has 1 place, and email is set up to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 206
      await testRunner.AndAsync("a Teams notification waits for its attempt 2 after a 429 with a retry after of 30" +
                        " seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
      await testRunner.WhenAsync("\"treasury-ops\" emails template \"account-opened\" to \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 208
      await testRunner.ThenAsync("the call is refused with \"QUEUE_FULL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 209
      await testRunner.AndAsync("the mail catcher receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Teams notification waiting after a 429 does not hold up the next one")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ATeamsNotificationWaitingAfterA429DoesNotHoldUpTheNextOne()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "41";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Teams notification waiting after a 429 does not hold up the next one", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Webhook answers are retried by their kind, at most 3 attempts in all", null, tagsOfRule);
#line 212
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub, and the delivery waits of 5 seconds and 30 seconds" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
      await testRunner.GivenAsync("email is set up to send to the mail catcher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 214
      await testRunner.AndAsync("the webhook answers the first post with 429 and a retry after of 10 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 215
      await testRunner.WhenAsync("\"treasury-ops\" posts a card to \"ops-alerts\" for customer \"Jane Tan\" and then emai" +
                        "ls \"john@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 216
      await testRunner.ThenAsync("the mail to \"john@example.com\" is sent before the card for \"Jane Tan\" is posted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 217
      await testRunner.AndAsync("the card for \"Jane Tan\" is posted on attempt 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A bad destination counts as not set, and the others still work")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("no webhook URL", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("an empty webhook URL", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("the webhook URL \"http://127.0.0.1/hook\"", "44", null)]
        [global::NUnit.Framework.TestCaseAttribute("the webhook URL \"hooks/finance\"", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("a webhook URL of 2,049 characters", "46", null)]
        public async global::System.Threading.Tasks.Task ABadDestinationCountsAsNotSetAndTheOthersStillWork(string fault, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A bad destination counts as not set, and the others still work", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Teams settings when it starts, and still starts", null, tagsOfRule);
#line 222
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 223
      await testRunner.GivenAsync(string.Format("the service started with sign-in on, Teams on, the destination \"ops-alerts\" point" +
                            "ing at the webhook stub, and the destination \"finance\" with {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 224
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to \"finance\" and then to \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 227
      await testRunner.ThenAsync("the call to \"finance\" is skipped with reason \"TeamsDestinationNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 228
      await testRunner.AndAsync("the webhook stub records 1 post, for \"ops-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A destination name that breaks the rule is not set")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ADestinationNameThatBreaksTheRuleIsNotSet()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "47";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A destination name that breaks the rule is not set", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Teams settings when it starts, and still starts", null, tagsOfRule);
#line 239
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 240
      await testRunner.GivenAsync("the service started with sign-in on, Teams on, and the destination \"Ops-Alerts\" p" +
                        "ointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 241
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 242
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 243
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 244
      await testRunner.ThenAsync("the call is skipped with reason \"TeamsDestinationNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 245
      await testRunner.AndAsync("the webhook stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A bad Teams setting leaves Teams not configured, and email still works")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        [global::NUnit.Framework.TestCaseAttribute("Teams on and a time limit of 0 seconds", "48", null)]
        [global::NUnit.Framework.TestCaseAttribute("Teams on and a time limit of 121 seconds", "49", null)]
        [global::NUnit.Framework.TestCaseAttribute("the Teams on/off value \"yes\"", "50", null)]
        [global::NUnit.Framework.TestCaseAttribute("Teams on and 101 destinations", "51", null)]
        public async global::System.Threading.Tasks.Task ABadTeamsSettingLeavesTeamsNotConfiguredAndEmailStillWorks(string fault, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("fault", fault);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A bad Teams setting leaves Teams not configured, and email still works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Teams settings when it starts, and still starts", null, tagsOfRule);
#line 248
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 249
      await testRunner.GivenAsync(string.Format("the service started with sign-in on, email set up to send to the mail catcher, Te" +
                            "ams settings with the destination \"ops-alerts\", and {0}", fault), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 250
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 251
      await testRunner.WhenAsync("\"treasury-ops\" posts a card to \"ops-alerts\" and emails \"jane@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 252
      await testRunner.ThenAsync("the Teams call is skipped with reason \"ChannelNotConfigured\", and the webhook stu" +
                        "b receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 253
      await testRunner.AndAsync("the mail catcher receives 1 mail to \"jane@example.com\", and no start-up entry is " +
                        "about Teams", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Teams settings change takes effect only at the next start")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ATeamsSettingsChangeTakesEffectOnlyAtTheNextStart()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "52";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Teams settings change takes effect only at the next start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The service checks its Teams settings when it starts, and still starts", null, tagsOfRule);
#line 263
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 264
      await testRunner.GivenAsync("the service started with Teams on and no destination", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 265
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 266
      await testRunner.AndAsync("the destination \"ops-alerts\" is added while the service runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
      await testRunner.WhenAsync("\"treasury-ops\" posts a card to \"ops-alerts\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 268
      await testRunner.ThenAsync("the call is skipped with reason \"TeamsDestinationNotConfigured\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 269
      await testRunner.AndAsync("the webhook stub receives nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("No value, destination name or signature reaches the logs, traces or kept records")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task NoValueDestinationNameOrSignatureReachesTheLogsTracesOrKeptRecords()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "53";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No value, destination name or signature reaches the logs, traces or kept records", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("No secret or personal data leaves through logs, traces or kept records", null, tagsOfRule);
#line 279
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 274
      await testRunner.GivenAsync("the service runs with sign-in on and tracing on, and Teams on with the destinatio" +
                        "n \"ops-alerts\" pointing at the webhook stub with the signature \"Wb-s1gn-7731\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 275
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 276
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 280
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"Jane Tan\" and account \"0012345678\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 281
      await testRunner.ThenAsync("the webhook stub records 1 post", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 282
      await testRunner.AndAsync("no log entry, metric, trace or kept idempotency record holds \"Jane Tan\", \"0012345" +
                        "678\", \"ops-alerts\" or \"Wb-s1gn-7731\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("The webhook\'s answer text never reaches the logs")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task TheWebhooksAnswerTextNeverReachesTheLogs()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "54";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The webhook\'s answer text never reaches the logs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("No secret or personal data leaves through logs, traces or kept records", null, tagsOfRule);
#line 285
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 274
      await testRunner.GivenAsync("the service runs with sign-in on and tracing on, and Teams on with the destinatio" +
                        "n \"ops-alerts\" pointing at the webhook stub with the signature \"Wb-s1gn-7731\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 275
      await testRunner.AndAsync("the template \"staff-account-opened\" has a Teams version", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 276
      await testRunner.AndAsync("\"treasury-ops\" is a caller allowed to send notifications", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 286
      await testRunner.GivenAsync("the webhook answers attempt 1 with 400 and the text \"Bad card for Jane Tan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 287
      await testRunner.WhenAsync("\"treasury-ops\" posts template \"staff-account-opened\" to the Teams destination \"op" +
                        "s-alerts\" for customer \"Jane Tan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 288
      await testRunner.ThenAsync("the attempt failure entry holds the status code 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 289
      await testRunner.AndAsync("no log entry holds \"Jane Tan\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A Teams outage does not touch the health check")]
        [global::NUnit.Framework.CategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ATeamsOutageDoesNotTouchTheHealthCheck()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "55";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A Teams outage does not touch the health check", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A Teams outage does not touch the health check", null, tagsOfRule);
#line 294
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 295
      await testRunner.GivenAsync("the service runs with sign-in on and Teams on, with the destination \"ops-alerts\" " +
                        "pointing at the webhook stub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 296
      await testRunner.AndAsync("the webhook stub is stopped", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 297
      await testRunner.WhenAsync("the cluster\'s liveness probe asks the health check without a token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 298
      await testRunner.ThenAsync("the answer is 200 with the status \"Healthy\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
