<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DKNet.Notification.Share\DKNet.Notification.Share.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DKNet.Notification.App.Tests"/>
    </ItemGroup>
</Project>
